### PR TITLE
Add AbstractVssApi, get/put/list api handlers

### PR DESCRIPTION
**Pull request by G8XSU**
Add AbstractVssApi, get/put/list api handlers

### CODE REVIEW

**Review by jkczyz — COMMENTED** [review]
Overall, this looks good. Is there any test code that you could add?

**Comment by G8XSU** [comment]
Added in #12

**Comment by jkczyz** [comment]
> Added in #12

No need to make separate PR for tests, IMO.

**Comment by G8XSU** [comment]
Closing as it was reviewed as part of #12

**Pull request closed without merging**
